telegram:
  useFirstNameInsteadOfUsername: true
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
  token: TELEGRAM_TOKEN
discord:
  skipOldMessages: true
  useNickname: false
  token: DISCORD_TOKEN
debug: true
bridges:
  - name: XP-Telegram
    direction: both
    telegram:
      chatId: -CHAT_ID
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
    discord:
      serverId: 'SERVER_ID'
      channelId: 'CHANNEL_ID'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
